baseURL: "https://blog.cristianaldea.com"
title: Starlog
copyright: "© [Cristian Aldea](https://www.cristianaldea.com) 2025"
theme: [PaperMod]

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
mainsections:
  - posts

minify:
  disableXML: true
  minifyOutput: true

pagination:
  pagerSize: 5

DefaultContentLanguage: "en"
languages:
  en:
    languageName: English
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: Search
          url: search/
          weight: 1
        - name: Tags
          url: tags/
          weight: 2
        # - identifier: categories
        #   name: Categories
        #   url: /categories/
        #   weight: 3
        - identifier: website
          name: cristianaldea.com
          url: https://www.cristianaldea.com
          weight: 4
  ro:
    languageName: "Română"
    weight: 2
    title: "Română"
    taxonomies:
      categories: categorii
      tag: etichete
      series: serie
    menu:
      main:
        - name: Cauta
          url: cauta/
          weight: 1
        - name: Etichete
          url: etichete/
          weight: 2
        # - identifier: categories
        #   name: Categories
        #   url: categories
        #   weight: 3
        - identifier: website
          name: cristianaldea.com
          url: https://www.cristianaldea.com
          weight: 4
    params:
      languageAltTitle: "Romanian"
      description: "Blogul lui Cristian Aldea"
      homeInfoParams:
        Title: "Bun venit la ⭐ Starlog ⭐"
        Content: |
          Salut! Sunt Cristian Aldea!

          Acesta este blogul meu personal, unde explorez și scriu despre subiecte care mă interesează.

          Lectură plăcută!
      taxonomies: # idk why but this is needed to show post tags
        categories: categorii
        tag: etichete
        series: serie

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Starlog
  description: "Cristian Aldea's Blog"
  keywords: [Blog, Starlog]
  author: Cristian Aldea
  images: ["c-logo-256.png"]
  DateFormat: "January 2, 2006"

  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "c-logo/32.png"
    favicon16x16: "c-logo/16.png"
    favicon32x32: "c-logo/32.png"
    apple_touch_icon: "c-logo/256.png"
    safari_pinned_tab: "c-logo/c-logo.svg"

  label:
    text: "Starlog"
    icon: /c-logo/c-logo.svg
    iconHeight: 35

  homeInfoParams:
    Title: "Welcome to ⭐ Starlog ⭐"
    Content: |
      Hi, I'm Cristian Aldea!

      This is my personal blog, where I explore and write about topics that interest me.

      Happy reading!

  socialIcons:
    - name: github
      url: "https://github.com/cristian-aldea"
    - name: linkedin
      url: "https://www.linkedin.com/in/cristianaldea"
    - name: mail
      url: "https://www.cristianaldea.com"

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  editPost:
    URL: "mailto:aldea.cristian@outlook.com?subject=Starlog Feedback"
    Text: "Leave Feedback" # edit text
    appendFilePath: false # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

outputs:
  home:
    - HTML
    - RSS
    - JSON

markup:
  goldmark:
    renderer:
      unsafe: true
